### ISSUE TITLE
Cannot build: Due to dependency on predix.websocket.client

### ISSUE THREAD

**Issue by patrick-bergeron** [PredixDev/predix-websocket-server#2]
Whether connected to GE Network (VPN) or outside of network, failed to build the project due to dependency on predix.websocket.client library. Why is the client a dependency of the server? Does this socket server support non 'predix.websocket.client' based clients?

`
[ERROR] Failed to execute goal on project predix-websocket-server: Could not resolve dependencies for project com.ge.predix.solsvc:predix-websocket-server:jar:2.1.16: Failed to collect dependencies at com.ge.predix.solsvc:predix-websocket-client:jar:2.1.17: Failed to read artifact descriptor for com.ge.predix.solsvc:predix-websocket-client:jar:2.1.17: Could not transfer artifact com.ge.predix.solsvc:predix-websocket-client:pom:2.1.17 from/to predix.repo (https://artifactory.predix.io/artifactory/PREDIX-EXT): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
`

**Comment by patrick-bergeron** [comment]
Appears that the predix-websocket-client is a dependency for the unit testing portion of the build.

**Comment by turnerth** [comment]
Please do the steps here to set up your artifactory.predix.io access 

https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1560&tag=1608&journey=Development%20tools%20and%20tips&resources=1565,1560

**Comment by patrick-bergeron** [comment]
Did that a long time ago. Why is this the only project that gives me problems?

**Comment by patrick-bergeron** [comment]
Nevermind. My artifactory account has been blocked due to recurrent login failures. Not sure how that happened. Thanks.

**Comment by turnerth** [comment]
there was a major predix login issue this morning.  Maybe that was why? you might need to file a support ticket to have them clear it out.
